#!/bin/sh
# XBT Tracker torrents, munin plugin by poiuty
# Thanks Sanasol & cx https://www.linux.org.ru/forum/admin/9400654
 
URL="http://anilibria.tv:2710/st"
 
if [ "$1" = "config" ]; then
                echo 'graph_title XBT Tracker torrents'
                echo 'graph_args --base 1000'          
                echo 'graph_category XBT Tracker'
                echo 'graph_info This graph shows the XBT Tracker torrents stat.'
 
                echo 'graph_vlabel torrents'
 
                echo 'torrents.label torrents'     
                echo 'torrents.info torrents stats'
 
                exit 0
        fi
 
curl -s --compressed $URL | sed -e 's,.*<tr><td>torrents<td class=ar>\([^<]*\).*,\1,g' | xargs -r printf "torrents.value %s\n"
